# Archivo netlify.toml en la raíz del proyecto
[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"

[[redirects]]
  from = "/politica-de-privacidad"
  to = "/politica-de-privacidad.html"
  status = 200